package com.classes;

public record Student(int id, String name, int votos) {

    public Student(){
        this(-1, "void", -1);
    }

    // Canonical constructor is automatically generated by the record
    // and does not need to be explicitly defined.

    public Student(int id, String name) {
        this(id, name, -1);
    }

}
